"""Add role_id to User model

Revision ID: c94af8301a59
Revises: 75fe97abcdc3
Create Date: 2025-04-22 19:17:30.257190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c94af8301a59'
down_revision: Union[str, None] = '75fe97abcdc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_definition_roles')
    op.drop_index('ix_departments_id', table_name='departments')
    op.drop_table('departments')
    op.drop_index('ix_metric_records_id', table_name='metric_records')
    op.drop_table('metric_records')
    op.drop_index('ix_employee_roles_role_id', table_name='employee_roles')
    op.drop_table('employee_roles')
    op.drop_index('ix_metric_definitions_id', table_name='metric_definitions')
    op.drop_table('metric_definitions')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('EMPLOYEE', 'SUPERVISOR', 'ADMIN', name='role_type_enum'), autoincrement=False, nullable=False),
    sa.Column('department_role', postgresql.ENUM('HEALTHCARE_SUPERVISOR', 'HEALTHCARE_ADMIN', 'HEALTHCARE_NURSE', 'USPS_SUPERVISOR', 'USPS_MAIL_CARRIER', 'USPS_OFFICE_ADMIN', 'TRANSPORTATION_DRIVER', 'TRANSPORTATION_DISPATCHER', 'ADMIN2', name='department_role_enum'), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='users_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('employee_id', name='users_employee_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('metric_definitions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('metric_definitions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('metric_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metric_type', postgresql.ENUM('PERFORMANCE', 'WELLNESS', name='metric_type_enum'), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('metric_formula', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metric_formula_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_aggregated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_numeric', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='metric_definitions_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='metric_definitions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_metric_definitions_id', 'metric_definitions', ['id'], unique=False)
    op.create_table('employee_roles',
    sa.Column('role_id', sa.INTEGER(), server_default=sa.text("nextval('employee_roles_role_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id', name='employee_roles_pkey'),
    sa.UniqueConstraint('role_name', name='employee_roles_role_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_employee_roles_role_id', 'employee_roles', ['role_id'], unique=False)
    op.create_table('metric_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metric_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metric_type', postgresql.ENUM('PERFORMANCE', 'WELLNESS', name='metric_type_enum'), autoincrement=False, nullable=False),
    sa.Column('value_numeric', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], name='metric_records_metric_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='metric_records_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='metric_records_pkey')
    )
    op.create_index('ix_metric_records_id', 'metric_records', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('departments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('USPS', 'HEALTHCARE', 'TRANSPORTATION', name='department_type_enum'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='departments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_departments_id', 'departments', ['id'], unique=False)
    op.create_table('metric_definition_roles',
    sa.Column('metric_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], name='metric_definition_roles_metric_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['employee_roles.role_id'], name='metric_definition_roles_role_id_fkey'),
    sa.PrimaryKeyConstraint('metric_id', 'role_id', name='metric_definition_roles_pkey')
    )
    # ### end Alembic commands ###
